### ISSUE TITLE
Reference or attach credential in another credentials

### ISSUE THREAD

**Issue by burnburn** [w3c/vc-imp-guide#4]
Moved from VCWG as per decision at VCWG Barcelona f2f March 2019.  See https://github.com/w3c/vc-data-model/issues/135.

**Comment by msporny** [comment]
@gannan08 could you please write a section on hashlinks and how to properly use them w/ VCs.

**Comment by David-Chadwick** [comment]
Depending on your risk profile, you may be willing to accept the VC ID URI as sufficient reference to another VC. If however, you want more assurance you should include the hash of the VC as well as its ID in the referencing VC

**Comment by David-Chadwick** [comment]
As an example, VC A and VC B are issued by the same issuer to the same subject at the same time. It is reasonably to assume that a verifier will equally trust both VCs, especially if they contain related information.
Now consider VC A references VC B by containing the VC ID of VC B inside it. I assert that this is adequate. Requiring this reference to contain the hash of VC B as well is overkill and unnecessary. Can you think of an attack that would require this extra field. I cannot, since a successful attack on VC B or VC A implies the same attack could be successful on the other.
Here is realistic example. VC A is a degree certificate, VC B is the transcript  of the marks used when computing the degree. VC A contains the ID of VC B. I see no reason for requiring the hash of VC B to be inside VC A.

**Comment by TallTed** [comment]
Basically, it all comes around again to verifier policy, which stringency should be based on the consequences of accepting false credentials.

Considering your semi-realistic example, reasonable security considerations would have the grade-recording system be somewhat separate from the degree-recording system.

A bad actor could conceivably gain access to the grade-recording system that generates VC B, and not to the degree-recording system that generates VC A, and use the grade-recording system to produce an illegitimate VC B with the same ID as the legitimate VC B contained within it, but with "perfect marks" (on whatever grade scale).

Now that bad actor presents their actual VC A (which says they achieved the degree, which they did) with their forged VC B (which says they received perfect marks), instead of their actual VC B (which says they received minimally passing marks).

You might say, "the verifier will check that the issuance timestamps of the two VCs are within n seconds of each other" -- but that is also going beyond the IDs of the VCs.

Policies of one verifier (who really only cares that the person received the degree) may dictate that the reflective VC IDs are sufficient. Policies of another verifier (who cares that all marks were above some level) may dictate that the reflective VC IDs plus the proximity of their issuance timestamps is sufficient. Policies of another verifier (who wants all candidates for a professorial position to have achieved only the highest marks for some courses) may dictate that the hash is required in addition to the reflective VC IDs, possibly also requiring the proximity of their issuance timestamps.

These example policies and verifiers are not compelling, because this example doesn't quickly lead me to a significant risk to be prevented. That does not mean that other examples do not exist.

**Comment by dmitrizagidulin** [comment]
(I'll be making a PR to address this section, on using hashlinks, this week.)

**Comment by dlongley** [comment]
Addressed by #51.
